language: node_js
sudo: true
dist: trusty
node_js:
  - "10"
  - "12"
install:
  - npm i
script: npm test
notifications:
  email:
    on_failure: change
    on_success: change
after_success:
  - npm run coveralls
